### ISSUE TITLE
Better clarify supported node versions

### ISSUE THREAD

**Issue by jr-cologne** [jr-cologne/gulp-starter-kit#36]
Hi there, dear Hacktoberfest contributors,

it would be good if we could better clarify which node versions are supported by this Gulp Starter Kit.

I think, it would be enough to add a more specific description of our requirements with regards to Node.js to our [README file](https://github.com/jr-cologne/gulp-starter-kit/blob/master/README.md). But, in case you've any better ideas how to better clarify supported node versions, feel free to suggest them.

Here's a quick list about what is involved in this issue:

- [ ] Comment here to let others know you would like to take this issue
- [ ] Follow our quick [contributing guide](https://github.com/jr-cologne/gulp-starter-kit#contributing) starting from step 2
- [ ] Check out the required node versions of the project's dependencies
- [ ] Consider v8+ as the requirement, but make sure all dependencies match this requirement
- [ ] Make your changes to the documentation to inform users about our supported node versions

All right, have fun and celebrate Hacktoberfest with us! 🎉 

Thank you very much in advance, I really appreciate your contribution!

Best regards,
@jr-cologne

**Comment by parikshitgupta1** [comment]
### **Hey** ![bitmoji](https://render.bitstrips.com/v2/cpanel/2196307c-2ceb-46f8-8bf4-4c3e3f34f93e-6f97b0bd-04bb-4ab7-ba76-db69e1517e0e-v1.png?transparent=1&palette=1&width=246)

**Comment by drishit96** [comment]
I would like to work on this

**Comment by drishit96** [comment]
For specifying a specific Node.js version, the `engines` field in package.json can be used.
As mentioned here: https://stackoverflow.com/a/29349773/5987223

**Comment by jr-cologne** [comment]
Cool, go for it! 👍 

Feel free to add the `engines` field to `package.json` as well.
