### ISSUE TITLE
scss files not gulping on save

### ISSUE THREAD

**Issue by presencewebdesign** [jr-cologne/gulp-starter-kit#41]
I couldn't figure out why it wouldn't gulp the .scss files when I saved the file. You had to save the main .sass file for it to gulp. 

The .scss files will not gulp because the destination has no folder scss, this need to change to sass

    src_assets_folder + "scss/**/*.scss",

replace with 

    src_assets_folder + "sass/**/*.scss",

**Comment by jr-cologne** [comment]
Hi @presencewebdesign,

thank you for filing this issue.
However, I don't feel like this is a bug.

As pointed out in the [README](https://github.com/jr-cologne/gulp-starter-kit#how-can-i-use-another-css-preprocessor-than-sass), the Gulp Starter Kit supports the four main CSS preprocessors Sass, SCSS, Less and Stylus. When using another preprocessor than the default, which is Sass, you have to rename the `sass` folder to `scss` or any other supported preprocessor in the same way.
If you follow this rule, everything should work as expected.

I hope this helps. In case I didn't understand you correctly, please point out your issue in more detail.

Kind regards,
@jr-cologne
